"""add request amount to idempotency keys

Revision ID: 2a35de4968d1
Revises: 0fc48c10d6b6
Create Date: 2026-05-08 07:25:04.164055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a35de4968d1'
down_revision: Union[str, Sequence[str], None] = '0fc48c10d6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_keys', sa.Column('request_amount', sa.Numeric(precision=18, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idempotency_keys', 'request_amount')
    # ### end Alembic commands ###
